openapi: 3.0.3
info:
  title: Australian Ad Observatory API
  description: 'This is the API for the Australian Ad Observatory.


    I will try to come up with a better description later.'
  termsOfService: http://swagger.io/terms/
  contact:
    email: d.k.tran@uq.edu.au
  license:
    name: MIT
    url: https://opensource.org/license/mit
  version: 1.0.0
externalDocs:
  description: Find out more about the Australian Ad Observatory
  url: https://www.admscentre.org.au/adobservatory/
servers:
- url: https://f06kj1k332.execute-api.ap-southeast-2.amazonaws.com/dev/
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
paths:
  /auth/login:
    post:
      summary: Log the user in and return a JSON web token.
      description: Log the user in and create a JSON web token for the user, which can be
        used to authenticate the user in future requests.
      
      tags:
      - auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        200:
          description: A successful login
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  token:
                    type: string
        400:
          description: A failed login
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  comment:
                    type: string
  /auth/verify:
    post:
      summary: Verify the JSON web token.
      description: Return whether the JSON web token is valid.
      
      tags:
      - auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
      responses:
        200:
          description: A successful verification
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
        400:
          description: A failed verification
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  comment:
                    type: string
                    example: VERIFY_FAILED
  /auth/logout:
    post:
      summary: Log the user out.
      description: Log the user out and disable the JSON web token to prevent further authentication
        using the same token.
      
      tags:
      - auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
      responses:
        200:
          description: A successful logout
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
        400:
          description: A failed logout
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  comment:
                    type: string
                    example: LOGOUT_FAILED
  /auth/refresh:
    post:
      summary: Refresh the JSON web token.
      description: Refresh the JSON web token to extend the session.
      
      tags:
      - auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
      responses:
        200:
          description: A successful refresh
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  token:
                    type: string
        400:
          description: A failed refresh
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  comment:
                    type: string
                    example: REFRESH_FAILED
  /users:
    get:
      summary: Returns a list of users from the database (admin only) [allows - admin]
      description: 'Returns a list of users stored in the database.
      
      
        This endpoint requires the authenticated user to have one of the following roles:
        **admin**.'
      
      tags:
      - users
      responses:
        200:
          description: A successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    username:
                      type: string
                    enabled:
                      type: boolean
                    password:
                      type: string
                    full_name:
                      type: string
                    role:
                      type: string
        400:
          description: A failed response
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  comment:
                    type: string
        403:
          description: Unauthorized access
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  comment:
                    type: string
                    example: UNAUTHORISED
      security:
      - bearerAuth: []
    post:
      summary: Create a new user (admin only) [allows - admin]
      description: 'Create a new user in the database.
      
      
        This endpoint requires the authenticated user to have one of the following roles:
        **admin**.'
      
      tags:
      - users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              required:
              - username
              - enabled
              - password
              - full_name
              - role
              type: object
              properties:
                username:
                  type: string
                enabled:
                  type: boolean
                password:
                  type: string
                full_name:
                  type: string
                role:
                  type: string
      responses:
        201:
          description: User created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  comment:
                    type: string
        400:
          description: User creation failed
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  comment:
                    type: string
                    example: User already exists
        403:
          description: Unauthorized access
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  comment:
                    type: string
                    example: UNAUTHORISED
      security:
      - bearerAuth: []
  /users/{username}:
    patch:
      summary: Edit a user's information (self or admin only) [allows - user, admin]
      description: 'Edit a user''s information. All fields are optional, and only the fields
        provided will be updated.
      
      
        This endpoint requires the authenticated user to have one of the following roles:
        **user, admin**.'
      
      parameters:
      - in: path
        name: username
        required: true
        schema:
          type: string
        description: The username of the user to edit
      tags:
      - users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                enabled:
                  type: boolean
                password:
                  type: string
                full_name:
                  type: string
                role:
                  type: string
      responses:
        200:
          description: A successful edit
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  comment:
                    type: string
        400:
          description: A failed edit
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  comment:
                    type: string
                    example: User not found
        403:
          description: Unauthorized edit
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  comment:
                    type: string
                    example: UNAUTHORISED
      security:
      - bearerAuth: []
    get:
      summary: Get a user from the database (self or admin only) [allows - user, admin]
      description: 'Get a user''s information stored in the database.
      
      
        This endpoint requires the authenticated user to have one of the following roles:
        **user, admin**.'
      
      parameters:
      - in: path
        name: username
        required: true
        schema:
          type: string
        description: The username of the user to get
      tags:
      - users
      responses:
        200:
          description: A successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    type: string
                  enabled:
                    type: boolean
                  password:
                    type: string
                  full_name:
                    type: string
                  role:
                    type: string
        400:
          description: A failed response
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  comment:
                    type: string
                    example: User not found
        403:
          description: Unauthorized access
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  comment:
                    type: string
                    example: UNAUTHORISED
      security:
      - bearerAuth: []
    delete:
      summary: Delete a user (admin only) [allows - admin]
      description: 'Delete a user by moving their data to the recycle bin.
      
      
        This endpoint requires the authenticated user to have one of the following roles:
        **admin**.'
      
      parameters:
      - in: path
        name: username
        required: true
        schema:
          type: string
        description: The username of the user to delete
      tags:
      - users
      responses:
        200:
          description: User deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  comment:
                    type: string
        400:
          description: User deletion failed
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  comment:
                    type: string
                    example: User not found
        403:
          description: Unauthorized access
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  comment:
                    type: string
                    example: UNAUTHORISED
      security:
      - bearerAuth: []
  /users/self:
    get:
      summary: Get the current user's information [allows - user, admin]
      description: 'Get the information of the user making the request.
      
      
        This endpoint requires the authenticated user to have one of the following roles:
        **user, admin**.'
      
      tags:
      - users
      responses:
        200:
          description: A successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    type: string
                  enabled:
                    type: boolean
                  password:
                    type: string
                  full_name:
                    type: string
                  role:
                    type: string
        400:
          description: A failed response
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  comment:
                    type: string
                    example: User not found
      security:
      - bearerAuth: []
  /ads/{observer_id}:
    get:
      summary: Retrieve the access cache for an observer.
      description: Retrieve the quick access cache for the specified observer.
      
      parameters:
      - in: path
        name: observer_id
        required: true
        schema:
          type: string
      tags:
      - ads
      responses:
        200:
          description: A successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    type: object
        400:
          description: A failed response
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  comment:
                    type: string
                    example: OBSERVER_NOT_PROVIDED_IN_PATH
        404:
          description: No cache found for observer
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  comment:
                    type: string
                    example: NO_CACHE_FOUND_FOR_OBSERVER
      security:
      - bearerAuth: []
  /ads/{observer_id}/{timestamp}.{ad_id}/stitching/frames:
    get:
      summary: Get the presigned URLs for the frames of an ad's stitching.
      description: Retrieve presigned URLs for the frames of the specified ad's stitching,
        which is the cropped version of the ad that removes the irrelevant parts.
      
      parameters:
      - in: path
        name: observer_id
        required: true
        schema:
          type: string
      - in: path
        name: timestamp
        required: true
        schema:
          type: string
      - in: path
        name: ad_id
        required: true
        schema:
          type: string
      tags:
      - ads
      responses:
        200:
          description: A successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  frame_paths:
                    type: array
                    items:
                      type: string
                  presigned_urls:
                    type: array
                    items:
                      type: string
        400:
          description: A failed response
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  comment:
                    type: string
                    example: PATH_NOT_PROVIDED
      security:
      - bearerAuth: []
  /ads/{observer_id}/{timestamp}.{ad_id}/frames:
    get:
      summary: Get the presigned URLs for the frames of an ad.
      description: Retrieve presigned URLs for the frames of the specified ad.
      
      parameters:
      - in: path
        name: observer_id
        required: true
        schema:
          type: string
      - in: path
        name: timestamp
        required: true
        schema:
          type: string
      - in: path
        name: ad_id
        required: true
        schema:
          type: string
      tags:
      - ads
      responses:
        200:
          description: A successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  frame_paths:
                    type: array
                    items:
                      type: string
                  presigned_urls:
                    type: array
                    items:
                      type: string
        400:
          description: A failed response
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  comment:
                    type: string
                    example: PATH_NOT_PROVIDED
      security:
      - bearerAuth: []
  /ads:
    get:
      summary: Retrieve the ads stream index.
      description: Retrieve the ads stream index from the S3 bucket, or recompute it if
        it is older than 24 hours.
      
      tags:
      - ads
      responses:
        200:
          description: A successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  presigned_url:
                    type: string
        500:
          description: A failed response
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  comment:
                    type: string
                    example: FAILED_TO_COMPUTE_ADS_STREAM_INDEX
                  error:
                    type: string
      security:
      - bearerAuth: []
  /observers:
    get:
      summary: List all observers. [allows - user, admin]
      description: 'Retrieve a list of all observers from the S3 bucket.
      
      
        This endpoint requires the authenticated user to have one of the following roles:
        **user, admin**.'
      
      tags:
      - observers
      responses:
        200:
          description: A successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        400:
          description: A failed response
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  comment:
                    type: string
      security:
      - bearerAuth: []
  /ads/{observer_id}/{timestamp}.{ad_id}/attributes:
    get:
      summary: Retrieve all attributes for an ad.
      description: Retrieve all custom attributes for the specified ad.
      
      parameters:
      - in: path
        name: observer_id
        required: true
        schema:
          type: string
      - in: path
        name: timestamp
        required: true
        schema:
          type: string
      - in: path
        name: ad_id
        required: true
        schema:
          type: string
      tags:
      - ads/attributes
      responses:
        200:
          description: A successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  ad_id:
                    type: string
                  observer:
                    type: string
                  timestamp:
                    type: integer
                  attributes:
                    type: object
                    additionalProperties:
                      type: object
                      properties:
                        value:
                          type: string
                        created_at:
                          type: integer
                        created_by:
                          type: string
                        modified_at:
                          type: integer
                        modified_by:
                          type: string
        400:
          description: A failed response
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  comment:
                    type: string
                    example: ERROR_RETRIEVING_ATTRIBUTES
      security:
      - bearerAuth: []
    put:
      summary: Add or update ad attributes in the database. [allows - user, admin]
      description: 'Add or update custom attributes for the specified ad in the database.
      
      
        This endpoint requires the authenticated user to have one of the following roles:
        **user, admin**.'
      
      parameters:
      - in: path
        name: observer_id
        required: true
        schema:
          type: string
      - in: path
        name: timestamp
        required: true
        schema:
          type: string
      - in: path
        name: ad_id
        required: true
        schema:
          type: string
      tags:
      - ads/attributes
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                attribute:
                  type: object
                  properties:
                    key:
                      type: string
                    value:
                      type: string
      responses:
        200:
          description: A successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  comment:
                    type: string
        400:
          description: A failed response
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  comment:
                    type: string
                    example: AD_NOT_FOUND
      security:
      - bearerAuth: []
  /ads/{observer_id}/{timestamp}.{ad_id}/attributes/{attribute_key}:
    get:
      summary: Retrieve a single attribute for an ad.
      description: Retrieve a specific custom attribute for the specified ad.
      
      parameters:
      - in: path
        name: observer_id
        required: true
        schema:
          type: string
      - in: path
        name: timestamp
        required: true
        schema:
          type: string
      - in: path
        name: ad_id
        required: true
        schema:
          type: string
      - in: path
        name: attribute_key
        required: true
        schema:
          type: string
      tags:
      - ads/attributes
      responses:
        200:
          description: A successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  key:
                    type: string
                  value:
                    type: string
                  created_at:
                    type: integer
                  created_by:
                    type: string
                  modified_at:
                    type: integer
                  modified_by:
                    type: string
        400:
          description: A failed response
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  comment:
                    type: string
                    example: ATTRIBUTE_NOT_FOUND
      security:
      - bearerAuth: []
    delete:
      summary: Delete ad attributes from the database. [allows - user, admin]
      description: 'Delete custom attributes for the specified ad in the database.
      
      
        This endpoint requires the authenticated user to have one of the following roles:
        **user, admin**.'
      
      parameters:
      - in: path
        name: observer_id
        required: true
        schema:
          type: string
      - in: path
        name: timestamp
        required: true
        schema:
          type: string
      - in: path
        name: ad_id
        required: true
        schema:
          type: string
      - in: path
        name: attribute_key
        required: true
        schema:
          type: string
      tags:
      - ads/attributes
      responses:
        200:
          description: A successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  comment:
                    type: string
        400:
          description: A failed response
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  comment:
                    type: string
                    example: ERROR_DELETING_ATTRIBUTE
      security:
      - bearerAuth: []
  /medias:
    get:
      summary: Get a media file from S3 from a given path in the query string.
      description: The path should be a key in the S3 bucket.
      
      tags:
      - media
      parameters:
      - in: query
        name: path
        required: true
        schema:
          type: string
        description: The path to the media file in the S3 bucket
      responses:
        200:
          description: A successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  path:
                    type: string
                  url:
                    type: string
        404:
          description: File not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  comment:
                    type: string
                    example: FILE_NOT_FOUND
      security:
      - bearerAuth: []
  /guest/sessions:
    post:
      summary: Create a guest session. [allows - admin, user]
      description: 'This endpoint requires the authenticated user to have one of the following
        roles: **admin, user**.'
      
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                key:
                  type: string
                  description: A unique identifier for the session.
                expiration_time:
                  type: integer
                  description: The time in seconds until the session expires.
                description:
                  type: string
                  description: A description of the session.
      responses:
        200:
          description: A JSON object containing the session token
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  token:
                    type: string
                example:
                  success: true
                  token: jwt_token
        400:
          description: A JSON object containing an error message
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  comment:
                    type: string
                example:
                  success: false
                  comment: Error message
      security:
      - bearerAuth: []
    get:
      summary: List all guest sessions. [allows - admin, user]
      description: 'This endpoint requires the authenticated user to have one of the following
        roles: **admin, user**.'
      
      responses:
        200:
          description: A JSON array containing session data
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    key:
                      type: string
                    data:
                      type: object
                example:
                - key: session_key
                  data:
                    exp: 1234567890
                    username: session_key
                    role: guest
                    enabled: true
                    full_name: Guest
                    description: Session description
      security:
      - bearerAuth: []
  /guest/sessions/{key}:
    get:
      summary: Retrieve a guest session. [allows - admin, user]
      description: 'This endpoint requires the authenticated user to have one of the following
        roles: **admin, user**.'
      
      parameters:
      - name: key
        in: path
        required: true
        schema:
          type: string
        description: The key of the session.
      responses:
        200:
          description: A JSON object containing the session token
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  token:
                    type: string
                example:
                  success: true
                  token: jwt_token
        404:
          description: A JSON object containing an error message
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  comment:
                    type: string
                example:
                  success: false
                  comment: Session not found
      security:
      - bearerAuth: []
    delete:
      summary: Delete a guest session. [allows - admin, user]
      description: 'This endpoint requires the authenticated user to have one of the following
        roles: **admin, user**.'
      
      parameters:
      - name: key
        in: path
        required: true
        schema:
          type: string
        description: The key of the session.
      responses:
        200:
          description: A JSON object indicating success
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  comment:
                    type: string
                example:
                  success: true
                  comment: Session deleted
        404:
          description: A JSON object containing an error message
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  comment:
                    type: string
                example:
                  success: false
                  comment: Session not found
      security:
      - bearerAuth: []
    patch:
      summary: Update a guest session. [allows - admin, user]
      description: 'This endpoint requires the authenticated user to have one of the following
        roles: **admin, user**.'
      
      parameters:
      - name: key
        in: path
        required: true
        schema:
          type: string
        description: The key of the session.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                description:
                  type: string
                  description: A new description for the session.
                expiration_time:
                  type: integer
                  description: A new expiration time for the session in seconds.
      responses:
        200:
          description: A JSON object indicating success
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  comment:
                    type: string
                example:
                  success: true
                  comment: Session updated
        404:
          description: A JSON object containing an error message
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  comment:
                    type: string
                example:
                  success: false
                  comment: Session not found
      security:
      - bearerAuth: []
  /reflect:
    post:
      summary: Reflect the event back to the client.
      description: Return the event object as the response.
      
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
      responses:
        200:
          description: A successful reflection
          content:
            application/json:
              schema:
                type: object
        400:
          description: A failed reflection
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  comment:
                    type: string
  /hello:
    get:
      responses:
        200:
          description: OK
        400:
          description: Bad Request
  /hello/{user_id}:
    get:
      parameters:
      - name: user_id
        in: path
        required: true
        schema:
          type: string
      responses:
        200:
          description: OK
        400:
          description: Bad Request
